export const commentsTypes = {
    GET_COMMENTS: 'GET COMMENTS',
    ADD_COMMENT: 'ADD COMMENT',
    DELETE_COMMENT: 'DELETE COMMENT',
    UPDATE_COMMENT: 'UPDATE COMMENT',
    IS_PROCESS: 'IS_PROCESS',
    EDIT_MODE: 'EDIT MODE',
}

export const asyncCommentsTypes = {
    ASYNC_GET_COMMENTS: 'ASYNC GET COMMENTS',
    ASYNC_ADD_COMMENT: 'ASYNC ADD COMMENT',
    ASYNC_DELETE_COMMENT: 'ASYNC DELETE COMMENT',
    ASYNC_UPDATE_COMMENT: 'ASYNC UPDATE COMMENT',
}